#Data preprocessing

##Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##Import Dataset



In [2]:
dataset = pd.read_csv('Placement.csv')

#Classification

##Split to Independant and Dependant variables

In [3]:
X = dataset.iloc[:, 1:-2]
y_placed = dataset.iloc[:, -2].values

In [4]:
X

gender  ssc_p    ssc_b  hsc_p  ... workex etest_p  specialisation  mba_p
0        M  67.00   Others  91.00  ...     No    55.0          Mkt&HR  58.80
1        M  79.33  Central  78.33  ...    Yes    86.5         Mkt&Fin  66.28
2        M  65.00  Central  68.00  ...     No    75.0         Mkt&Fin  57.80
3        M  56.00  Central  52.00  ...     No    66.0          Mkt&HR  59.43
4        M  85.80  Central  73.60  ...     No    96.8         Mkt&Fin  55.50
..     ...    ...      ...    ...  ...    ...     ...             ...    ...
210      M  80.60   Others  82.00  ...     No    91.0         Mkt&Fin  74.49
211      M  58.00   Others  60.00  ...     No    74.0         Mkt&Fin  53.62
212      M  67.00   Others  67.00  ...    Yes    59.0         Mkt&Fin  69.72
213      F  74.00   Others  66.00  ...     No    70.0          Mkt&HR  60.23
214      M  62.00  Central  58.00  ...     No    89.0          Mkt&HR  60.22

[215 rows x 12 columns]

In [5]:
X.dtypes

gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
dtype: object

##Encoding categorical data

###encoding independent variable

In [6]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
ct = make_column_transformer(
    (StandardScaler(), make_column_selector(dtype_include=np.number)),
    (OneHotEncoder(), make_column_selector(dtype_include=object))
)

X = (ct.fit_transform(X))
X = np.array(X)

In [7]:
len(X[0])

21

###encoding dependent variable (y_placed)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_placed = le.fit_transform(y_placed)

In [9]:
y_placed

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

##Split train and test set

```
# This is formatted as code
```



In [10]:
from sklearn.model_selection import train_test_split
X_placed_train, X_placed_test, y_placed_train, y_placed_test = train_test_split(X, y_placed, test_size = 0.25)

##Build ANN for classification

In [11]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

##Train the ANN

###Compile the ANN

In [12]:
ann.compile(optimizer='adam',
            loss = 'binary_crossentropy',
            metrics = ['accuracy'])

###Train the ANN on training set

In [13]:
ann.fit(X_placed_train, y_placed_train, batch_size = 8, epochs = 75)

Epoch 1/75
21/21 [==============================] - 0s 1ms/step - loss: 0.6812 - accuracy: 0.6584
Epoch 2/75
21/21 [==============================] - 0s 1ms/step - loss: 0.6627 - accuracy: 0.7143
Epoch 3/75
21/21 [==============================] - 0s 1ms/step - loss: 0.6454 - accuracy: 0.7205
Epoch 4/75
21/21 [==============================] - 0s 1ms/step - loss: 0.6259 - accuracy: 0.6894
Epoch 5/75
21/21 [==============================] - 0s 1ms/step - loss: 0.6078 - accuracy: 0.6894
Epoch 6/75
21/21 [==============================] - 0s 1ms/step - loss: 0.5894 - accuracy: 0.6832
Epoch 7/75
21/21 [==============================] - 0s 1ms/step - loss: 0.5712 - accuracy: 0.6832
Epoch 8/75
21/21 [==============================] - 0s 1ms/step - loss: 0.5539 - accuracy: 0.6832
Epoch 9/75
21/21 [==============================] - 0s 1ms/step - loss: 0.5368 - accuracy: 0.6832
Epoch 10/75
21/21 [==============================] - 0s 1ms/step - loss: 0.5201 - accuracy: 0.6832
Epoch 11/75
21/21 [

##Making prediction and evaluating the model (Classification)

###Predict the test set

In [14]:
y_placed_pred = ann.predict(X_placed_test)
y_placed_pred = (y_placed_pred > 0.5)

### Make the confusion matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_placed_test, y_placed_pred)
print(cm)
accuracy_score(y_placed_test, y_placed_pred)

[[10  5]
 [ 5 34]]


0.8148148148148148

#Regression

##Remove people with no placements

In [16]:
dataset_salary = dataset.dropna()

In [17]:
dataset_salary

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p  status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80  Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28  Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80  Placed  250000.0
4        5      M  85.80  Central  ...         Mkt&Fin  55.50  Placed  425000.0
7        8      M  82.00  Central  ...         Mkt&Fin  62.14  Placed  252000.0
..     ...    ...    ...      ...  ...             ...    ...     ...       ...
209    210      M  62.00  Central  ...         Mkt&Fin  56.49  Placed  216000.0
210    211      M  80.60   Others  ...         Mkt&Fin  74.49  Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62  Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72  Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23  Placed  204000.0

[148 rows x 15 columns]

##Split to Independant and Dependant variables

In [18]:
X_salary = dataset_salary.iloc[:, 1:-2]
y_salary = dataset_salary.iloc[:, -1].values

In [19]:
X_salary

gender  ssc_p    ssc_b  hsc_p  ... workex etest_p  specialisation  mba_p
0        M  67.00   Others  91.00  ...     No    55.0          Mkt&HR  58.80
1        M  79.33  Central  78.33  ...    Yes    86.5         Mkt&Fin  66.28
2        M  65.00  Central  68.00  ...     No    75.0         Mkt&Fin  57.80
4        M  85.80  Central  73.60  ...     No    96.8         Mkt&Fin  55.50
7        M  82.00  Central  64.00  ...    Yes    67.0         Mkt&Fin  62.14
..     ...    ...      ...    ...  ...    ...     ...             ...    ...
209      M  62.00  Central  72.00  ...     No    67.0         Mkt&Fin  56.49
210      M  80.60   Others  82.00  ...     No    91.0         Mkt&Fin  74.49
211      M  58.00   Others  60.00  ...     No    74.0         Mkt&Fin  53.62
212      M  67.00   Others  67.00  ...    Yes    59.0         Mkt&Fin  69.72
213      F  74.00   Others  66.00  ...     No    70.0          Mkt&HR  60.23

[148 rows x 12 columns]

In [20]:
y_salary

array([270000., 200000., 250000., 425000., 252000., 231000., 260000.,
       250000., 218000., 200000., 300000., 236000., 265000., 393000.,
       360000., 300000., 360000., 240000., 265000., 350000., 250000.,
       278000., 260000., 300000., 320000., 240000., 411000., 287000.,
       300000., 200000., 204000., 250000., 200000., 450000., 216000.,
       220000., 240000., 360000., 268000., 265000., 260000., 300000.,
       240000., 240000., 275000., 275000., 275000., 360000., 240000.,
       240000., 218000., 336000., 230000., 500000., 270000., 240000.,
       300000., 300000., 300000., 400000., 220000., 210000., 210000.,
       300000., 230000., 260000., 420000., 300000., 220000., 380000.,
       300000., 240000., 360000., 200000., 300000., 250000., 250000.,
       280000., 250000., 216000., 300000., 240000., 276000., 940000.,
       250000., 236000., 240000., 250000., 350000., 210000., 250000.,
       400000., 250000., 360000., 300000., 250000., 250000., 200000.,
       225000., 2500

##Encoding independent variable

In [21]:
ct = make_column_transformer(
    (StandardScaler(), make_column_selector(dtype_include=np.number)),
    (OneHotEncoder(), make_column_selector(dtype_include=object))
)

X_salary = ct.fit_transform(X_salary)
X_salary = np.array(X_salary)

In [22]:
len(X_salary)

148

##Split to train and test set

In [23]:
X_salary_train, X_salary_test, y_salary_train, y_salary_test = train_test_split(X_salary,
                                                                                y_salary,
                                                                                test_size = 0.20)

##Train a Random Forest Regression Model

In [31]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10)
regressor.fit(X_salary_train, y_salary_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

##Predict based on Random Forest Regression

In [32]:
y_salary_pred = regressor.predict(X_salary_test)

##Evaluate Random Forest Regression

In [35]:
from sklearn.metrics import r2_score
r2_score(y_salary_test, y_salary_pred)

-0.27242313103468563